### ISSUE TITLE
seg fault on unexpected char

### ISSUE THREAD

**Issue by mewalig** [jgarzik/sqlfun#1]
Thanks for putting this together. I have that Flex+Bison book too!

The following will create a seg fault:
    echo "select [ab] from d;" | ./sql

The reason is that in ```sql.l``` the call to yyerror is missing a parameter. The fix is to replace all occurrences of ```yyerror(yylloc, 0, pstate``` with ````yyerror(yylloc, 0, pstate````

**Comment by mewalig** [comment]
I meant, replace
```yyerror(yylloc, pstate```
    with
```yyerror(yylloc, 0, pstate```

**Comment by jgarzik** [comment]
@mewalig There was a mismatch of yyerror() prototypes, where `yyerror` was missing the `yyscan_t scanner` second argument.  The patch updated a broken prototype, and supplied the missing pstate->scanner argument.

Are you saying that yyscan_t should be null?

**Comment by mewalig** [comment]
Not as much saying it should be null, as saying only that it should be present. It actually doesn't matter what it is-- in sql.tab.c, the definition of yyerror() does not use the scanner argument. of course, you could instead try to find a way to generate the function with a different signature altogether, but it seemed easier to just pass it a NULL arg:
```
void
yyerror(YYLTYPE *t, yyscan_t scanner, struct psql_state *pstate, const char *s, ...)
{
  va_list ap;
  va_start(ap, s);
  
  if(t->first_line)
    fprintf(stderr, "%s:%d.%d-%d.%d: error: ", t->filename, t->first_line, t->first_column,
	    t->last_line, t->last_column);
  vfprintf(stderr, s, ap);
  fprintf(stderr, "\n");
}
```
